# Generated by Django 4.2.8 on 2024-03-10 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='course_pay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_pay', to='lms.course', verbose_name='курс'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='lesson_pay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_pay', to='lms.lesson', verbose_name='урок'),
        ),
    ]
